# Generated by Django 4.2.23 on 2025-08-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPadraoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_padrao', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Horário Padrão',
                'verbose_name_plural': 'Horários Padrão',
                'ordering': ['dia_semana', 'horario_inicio'],
                'unique_together': {('aluno', 'dia_semana', 'horario_inicio')},
            },
        ),
    ]
