# Generated by Django 4.2.23 on 2025-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_horariopadraoaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Descreva os objetivos do aluno...'),
        ),
    ]
