# Generated by Django 4.2.23 on 2025-08-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, help_text='Percentual de gordura corporal', max_digits=4, null=True)),
                ('ombro', models.DecimalField(blank=True, decimal_places=1, help_text='Medida do ombro em cm', max_digits=4, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=1, help_text='Medida do tórax em cm', max_digits=4, null=True)),
                ('braco', models.DecimalField(blank=True, decimal_places=1, help_text='Medida do braço em cm', max_digits=4, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=1, help_text='Medida do quadril em cm', max_digits=4, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=1, help_text='Medida da cintura em cm', max_digits=4, null=True)),
                ('coxa', models.DecimalField(blank=True, decimal_places=1, help_text='Medida da coxa em cm', max_digits=4, null=True)),
                ('panturrilha', models.DecimalField(blank=True, decimal_places=1, help_text='Medida da panturrilha em cm', max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, help_text='IMC calculado automaticamente', max_digits=4, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre as medidas do mês')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos_mensais', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Acompanhamento Mensal',
                'verbose_name_plural': 'Acompanhamentos Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('aluno', 'ano', 'mes')},
            },
        ),
    ]
