# Generated by Django 4.2.23 on 2025-08-18 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0003_alter_aluno_objetivo'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='Mês de referência da fatura')),
                ('ano_referencia', models.IntegerField(help_text='Ano de referência da fatura')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da fatura', max_digits=8)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento da fatura')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atrasada', 'Atrasada'), ('paga', 'Paga')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento (quando pago)', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a fatura')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_simples', to='alunos.aluno')),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_simples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura Simples',
                'verbose_name_plural': 'Faturas Simples',
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'unique_together': {('aluno', 'mes_referencia', 'ano_referencia')},
            },
        ),
    ]
