# Generated by Django 4.2.23 on 2025-09-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_faturasimples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturasimples',
            name='ano_referencia',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034')], help_text='Ano de referência da fatura'),
        ),
    ]
