# Generated by Django 4.2.23 on 2025-08-11 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0007_tiponotificacao_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='horario_preferencial',
            field=models.TimeField(default=datetime.time(1, 9, 21, 760066)),
        ),
        migrations.AlterField(
            model_name='notificacaoautomatica',
            name='horario_envio',
            field=models.TimeField(default=datetime.time(1, 9, 21, 758816), help_text='Horário preferencial para envio'),
        ),
    ]
